name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@1.3.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: csc3150
        dockerfile-location: ./
